image: oliskir/kadlu:v0.0.1

stages:
   - build
   - test
   - deploy
   - trig

before_script:
   - source activate kadlu_env 
   - 'echo -e "\nurl: https://cds.climate.copernicus.eu/api/v2\nkey: 20822:2d1c1841-7d27-4f72-bb8a-9680a073b4c3\n" > /root/.cdsapirc'

run-tests:
 type: test
 script:
  - pytest --doctest-modules kadlu/

create-docs:
 type: deploy
 before_script: # overwrites global before_script
  - source activate kadlu_env
  - pip install --upgrade pip
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - cd docs/ && pip install sphinx_mer_rtd_theme-0.4.3.dev0.tar.gz && cd ..
  script:
   - cd docs/ && make html && cd ..
  only:
   - master

create-package:
 type: deploy
 script:
  - source activate kadlu_env
  - python setup.py sdist
  - pip install dist/kadlu-0.0.1.tar.gz
 only:
  - master
 artifacts:
  paths:
   - dist/kadlu-0.0.1.tar.gz

