image: oliskir/kadlu:conda_test1

stages:
- build
- test
- deploy
- trig


before_script:
  - source activate kadlu_env

run-tests:
 type: test
 script:
  - pytest

create-docs:
 type: deploy
 before_script: # overwrites global before_script
  - pip install --upgrade pip
  - pip install sphinx
  - pip install sphinx_rtd_theme
 script:
  - cd docs/ && make html && cd ..
 only:
  - master

create-package:
 type: deploy
 script:
  - python setup.py sdist
  - pip install dist/kadlu-0.0.1.tar.gz
 only:
  - master
 artifacts:
  paths:
   - dist/kadlu-0.0.1.tar.gz
