name: kadlu_env
channels:
  - conda-forge
  - defaults
dependencies:
  - make
  - pip
  - pytest
  - numpy
  - scipy
  - matplotlib
  - cython
  - setuptools
  - cftime
  - netCDF4
  - h5py
  - GDAL
  - tqdm
  - gsw
