name: kadlu_env
channels:
  - conda-forge
dependencies:
  - python=3
  - cartopy
  #- cftime
  - cdsapi
  - cython
  - geos
  - gsw
  #- h5py
  - imageio
  - jupyter
  - make
  - matplotlib
  - mpl_scatter_density
  - netCDF4
  - numpy
  - pandas
  - Pillow
  - pip
  - Proj
  - pygrib
  - pyproj
  - pyqt5
  - pytest
  - scipy
  - setuptools
  #- tqdm

