name: kadlu_env
channels:
  #  - defaults
  - conda-forge
dependencies:
  - make
  - pip
  - pytest
  - numpy
  - pandas
  - scipy
  - matplotlib
  - cython
  - setuptools
  - cftime
  - netCDF4
  - h5py
  - GDAL
  - pygrib
  - cdsapi
  - tqdm
  - gsw
  - cartopy
  - imageio

