name: kadlu_env
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - cdsapi
  - cython
  - gsw
  #- h5py
  - imageio
  - jupyter
  - make
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - Pillow
  - pip
  - pytest
  - pygrib
  - scipy
  - setuptools
  - tqdm

